name: IWFilms
favicon: null
layout_spectrum: 0.50764
typography_spectrum: 0.74782
title: IWanna Films Producciones Ltda
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#022550'
    - '#f0ddc6'
    - '#0d62a8'
    - '#4e8dca'
    - '#c68647'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
