name: IWFilms
favicon: null
layout_spectrum: 0.7631
typography_spectrum: 0.06004
title: IWanna Films Producciones Ltda
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a71a2'
    - '#ffffff'
    - '#1d1010'
    - '#f80c1a'
    - '#fc583a'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
